### ISSUE TITLE
Internal service error when linking to TripAdvisor

### ISSUE THREAD

**Issue by stragu** [OpenPlaceReviews/website#129]
I just joined OPR and tried to do my first edit by linking [this cafe](https://openplacereviews.org/data/objects/opr_place?key=5R4MG2,fdaxkb) to [its TripAdvisor page](https://www.tripadvisor.com/Restaurant_Review-g255068-d23824907-Reviews-Alphabet_Cafe-Brisbane_Brisbane_Region_Queensland.html).

I got this error:

![Error message: "Something went wrong. Internal service error."](https://user-images.githubusercontent.com/1747497/150453087-65bfc1b6-3802-41e6-b4a6-79916368bfcd.png)

OSM object is: https://www.openstreetmap.org/node/5140688128

**Comment by vshcherb** [comment]
I think this is correct link https://openplacereviews.org/map/opr.place/5R4MG2,fdaxkb

**Comment by vshcherb** [comment]
And I linked with a flaw. Please try to logout / login and we will keep an eye on the logs and comments.

**Comment by stragu** [comment]
OK it seems to work now, I tried with two other cafes.
What was the issue?

**Comment by vshcherb** [comment]
Not clear so far, keep waitching
