### ISSUE TITLE
502 Bad Gateway when trying to sign up

### ISSUE THREAD

**Issue by stragu** [OpenPlaceReviews/website#19]
Does anyone else get a 502 error when trying to sign up on https://openplacereviews.org/accounts/social/signup/ ?

I am trying on Firefox 68.0.1 and Chromium 76.0.3809.87 on Ubuntu 18.04.

**Comment by vshcherb** [comment]
Indeed. Accepted, planning to get back to UI next week. This is week, we are planning to rollout 1st release of blockchain.

**Comment by amenk** [comment]
probably not an issue anymore?

**Comment by vshcherb** [comment]
Yes it's fixed
