### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by camelCaseNick** [OpenPlaceReviews/website#20]
I get a

    HTTP/1.1 302 Found
    [...]
    Location: /accounts/login/?next=/profile/edit/

from `/profile/edit/` with a _Error login in OpenDB: No message available_ and _Successfully logged in site as [...]._ when logging in via OpenStreetMap. (Might be no problem of the website, but instead of OpenDB, though Idk.)

Note: My account, though I got an e-mail, is not in https://dev.openplacereviews.org/api/admin?view=objects&browse=type&type=sys.signup&subtype=all . Is that intended?

**Comment by vshcherb** [comment]
Thanks, it is a problem on website, we changed API underneath and still need to update website

**Comment by amenk** [comment]
I don't think this is an issue anymore? can probably be closed?
